version: '3.0'
services:
  db:
    image: postgres
    container_name: user
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test
      TZ: 'Asia/Seul'
